logging:
    level:
        blog: WARN
        net:
            guides: DEBUG
        org: WARN
        org.hibernate: ERROR
        org.springframework.web: INFO
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 1234
        url: jdbc:mysql://localhost:3306/training?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
    mail:
        host: smtp.gmail.com
        password: xncusxjihlhekoxp
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: training.program.suport@gmail.com
